FROM python:3.11-slim
WORKDIR /app

COPY src/requirements_tg.txt /app/requirements_tg.txt
COPY src/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir \
    --default-timeout=300 --retries=10 \
    -r /app/requirements_tg.txt \
    -r /app/requirements.txt

COPY src/ /app/

CMD ["python", "run_tg_bot.py"]
